=== gyulanemeth/ITK-Stock/ServerConfig.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:element name="server_config">
		<xs:complexType>
			<xs:sequence>
			
				<xs:element name="connection"> 
					<xs:complexType>
						<xs:sequence>
							<xs:element name="port" type="xs:integer"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			
				<xs:element name="db">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="dbHost" type="xs:string"/>
							<xs:element name="dbName" type="xs:string"/>
							<xs:element name="dbUser" type="xs:string"/>
							<xs:element name="dbPass" type="xs:string"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			
			</xs:sequence>
		</xs:complexType>
	</xs:element>

</xs:schema>

=== gyulanemeth/ITK-Stock/ServerConfig.xml
<?xml version="1.0" encoding="UTF-8"?>
<xsi:server_config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ServerConfig.xsd">
  <connection>
    <port>3306</port>
  </connection>
  
  <db>
    <dbHost>localhost</dbHost>
    <dbName>itkStock</dbName>
    <dbUser>itkStock</dbUser>
    <dbPass>itkStock</dbPass>
  </db>
</xsi:server_config>
